"use client";
import Link from "next/link";
import { useState } from "react";
import { useRewards, rewardsClient } from "./client";
import { rewardReasons, type RewardTask } from "./catalogue";
import { RewardsNavigation } from "./navigation";
import { ProofDialog } from "./proof-dialog";
import styles from "./rewards.module.css";
const date = (value: string) => new Date(value).toLocaleDateString("en-AU", { day: "numeric", month: "short", year: "numeric" });
const labels = { checking: "Pending assessment", approved: "Approved", "needs-evidence": "More photos needed", unavailable: "Retry needed" };
export function RewardsPage() {
  const { account, wallet, loading, error, busyTask } = useRewards();
  const [selected, setSelected] = useState<(RewardTask & { owner: string }) | null>(null);
  const [filter, setFilter] = useState("All");
  const attempts = wallet?.attempts.filter(item => filter === "All" || filter === "Pending" && item.status === "checking" || filter === "Approved" && item.status === "approved" || filter === "Retry needed" && ["needs-evidence", "unavailable"].includes(item.status)) ?? [];
  return <div className={styles.page}><RewardsNavigation />
    <section className={styles.hero} aria-labelledby="rewards-title"><div><h1 id="rewards-title">Small steps.<br /><span>Useful rewards.</span></h1><p className={styles.intro}>Earn coins for following through on your home’s next steps.</p><p>Choose a recommended task, send your photos, and see the result in Approvals. Approved tasks add coins automatically.</p><a className={styles.primary} href="#earn">{account.user ? "Find a task to earn coins" : "See how to earn coins"}</a></div>
      <aside className={styles.wallet} aria-label="Your coin balance"><svg viewBox="0 0 260 110" fill="none" aria-hidden="true"><circle cx="210" cy="26" r="18" fill="#ffb13b" /><path d="M28 103H244M53 103V42L126 10L199 42V103M42 44L126 6L210 44M86 53H165V103H86ZM126 53V103M86 77H165" stroke="#8da493" strokeWidth="2" /><path d="M81 50H171L158 35H94Z" fill="#b6c8b0" /></svg><span>Available coins</span><p className={styles.balance} aria-live="polite">{wallet ? wallet.balance.toLocaleString("en-AU") : "—"} <small>coins</small></p>{wallet ? <p>{wallet.completed} task{wallet.completed === 1 ? "" : "s"} approved. {wallet.earned} coins earned in total.</p> : <p>{account.user ? "Loading your private wallet…" : "Sign in to earn coins and keep your approvals."}</p>}<Link href={account.user ? "/marketplace" : "/sign-in"}>{account.user ? "Explore the marketplace" : "Sign in to earn coins"} ↗</Link><small>Prototype coins have no cash value. Marketplace coupons are demos.</small></aside>
    </section>
    <ol className={styles.how}><li><strong>Complete a task</strong><span>Use the recommendations for your room.</span></li><li><strong>Submit your photos</strong><span>Follow the task’s photo guide.</span></li><li><strong>Receive your coins</strong><span>Coins are added after automated approval.</span></li></ol>
    {error && <div role="alert" className={styles.error}>{error} <button onClick={() => void rewardsClient.refresh()}>Retry loading rewards</button></div>}
    <section id="earn" className={styles.section} aria-labelledby="earn-title"><div className={styles.sectionHeading}><div><h2 id="earn-title">Tasks you can earn from</h2><p>Based on your saved recommendations. Each task can earn coins once.</p></div>{account.user && <button className={styles.secondary} onClick={() => void rewardsClient.refresh()} disabled={loading}>{loading ? "Refreshing…" : "Refresh tasks"}</button>}</div>
      {!account.ready ? <p role="status">Opening your account…</p> : !account.user ? <div className={styles.empty}><h3>Start with your home</h3><p>Sign in and save your room assessment to see tasks suited to your recommendations.</p><Link href="/sign-in" className={styles.primary}>Sign in</Link> <Link href="/assessment">Explore the assessment</Link></div> : !wallet ? <p role="status">{error ? "Retry loading to see your tasks and saved coins." : "Loading your recommended tasks…"}</p> : !wallet.tasks.length ? <div className={styles.empty}><h3>Your recommendations come first</h3><p>Complete your room assessment and save it to your account. Photo-supported tasks will appear here where suitable.</p><Link href="/assessment" className={styles.primary}>Continue my assessment</Link></div> : <ul className={styles.tasks}>{wallet.tasks.map(task => {
        const attempt = wallet.attempts.find(item => item.taskId === task.id);
        const claimed = attempt?.status === "approved";
        const checking = attempt?.status === "checking" || busyTask === task.id;
        return <li key={task.id}><div className={styles.taskText}><small>{task.inPlan ? "In your room plan" : "From your recommendations"}</small><h3>{task.title}</h3><p>{task.detail}</p><p className={styles.photoGuide}>{task.proof}</p><small>{task.photoCount} photo{task.photoCount === 2 ? "s" : ""} required</small></div><div className={styles.taskAction}><strong>{claimed ? "✓ " : "+"}{task.coins} <span>coins</span></strong>{claimed ? <a href="#approvals">Approved · coins added</a> : checking ? <a href="#approvals">Pending assessment</a> : <button className={styles.primary} disabled={Boolean(busyTask) || !wallet.assessmentAvailable || account.phase !== "saved"} onClick={() => setSelected({ ...task, owner: account.user!.id })}>{attempt ? "Retry with photos" : "Submit photo proof"}</button>}</div></li>;
      })}</ul>}
      {wallet && !wallet.assessmentAvailable && <p role="status" className={styles.feedback}>Photo assessment is currently unavailable. Your saved coins are safe; try again later.</p>}
      {account.user && account.phase !== "saved" && <p className={styles.feedback}>Finish saving your account journey before submitting photos. <Link href="/account">Open My account</Link>.</p>}
      <p className={styles.small}>Some recommendations describe habits or work that photos cannot establish. They stay in your room plan without a coin award.</p>
    </section>
    <section id="approvals" className={styles.section} aria-labelledby="approvals-title"><div className={styles.sectionHeading}><div><h2 id="approvals-title">Your approvals</h2><p>Track photo submissions and see exactly when coins were added.</p></div>{wallet && <button className={styles.secondary} disabled={loading} onClick={() => void rewardsClient.refresh()}>Refresh approvals</button>}</div>
      <div className={styles.filters} role="group" aria-label="Approval status">{["All", "Pending", "Approved", "Retry needed"].map(value => <button key={value} aria-pressed={filter === value} onClick={() => setFilter(value)}>{value}</button>)}</div>
      {busyTask && <p role="status" className={styles.feedback}>Your photos are being checked. Keep this page open or return to see the saved result.</p>}
      {attempts.length ? <ul className={styles.approvals}>{attempts.map(attempt => <li key={attempt.id}><div><strong>{attempt.title}</strong><p><span className={styles.status} data-status={attempt.status}>{labels[attempt.status]}</span> <time dateTime={attempt.createdAt}>{date(attempt.createdAt)}</time></p>{attempt.reason && <p>{rewardReasons[attempt.reason]}</p>}</div><span className={styles.award}>{attempt.status === "approved" ? `+${attempt.coins} coins added` : "No coins added"}</span></li>)}</ul> : <div className={styles.empty}><h3>{filter === "All" ? "Your first approval starts with a task" : `No ${filter.toLowerCase()} submissions`}</h3><p>{filter === "All" ? "Submit photos using the task guide above. The result and coin award will appear here." : "Choose another status or submit a task photo."}</p></div>}
    </section>
    <section className={styles.section} aria-labelledby="history-title"><h2 id="history-title">Coin history</h2><p>Approved tasks add coins. Demo coupon redemptions use them.</p>{wallet?.entries.length ? <ul className={styles.history}>{wallet.entries.map(entry => <li key={entry.id}><div><strong>{entry.title}</strong><small>{entry.delta > 0 ? "Task approved" : "Demo coupon generated"} · {date(entry.createdAt)}</small></div><span>{entry.delta > 0 ? "+" : "−"}{Math.abs(entry.delta)} coins</span></li>)}</ul> : <p className={styles.small}>Your coin activity will appear here after your first approval.</p>}</section>
    {selected && wallet && selected.owner === account.user?.id && <ProofDialog key={`${selected.owner}-${selected.id}`} task={selected} busy={busyTask === selected.id} close={() => setSelected(null)} />}
  </div>;
}
