import test from "node:test";
import assert from "node:assert/strict";
import { activeQuestions, CORE_QUESTION_IDS, EQUIPMENT_QUESTION_IDS, questions } from "../src/features/assessment/questions.ts";
import { answerFor, emptyAssessment, updateAnswer, moveAssessment, canSeeAssessment, isAssessmentDraft, resumeAssessment, type AssessmentDraft } from "../src/features/assessment/state.ts";
import { assessmentScene, sceneFocus } from "../src/features/room-scene/assessment-scene.ts";
import { equipmentPlacement, equipmentDetailText } from "../src/features/room-scene/equipment-details.ts";
import { confirmScene } from "../src/features/room-scene/confirm-scene.ts";
import { materialSignature } from "../src/domain/material-signature.ts";
import { assessmentInput } from "../src/contracts/journey.ts";
import { isPlannerCommand } from "../src/contracts/validation.ts";
import { allowedIntakeQuestions } from "../src/features/assessment/intake-questions.ts";
import type { AnswerValue } from "../src/domain/models.ts";
const at = "2026-10-03T08:00:00Z";
function answer(d: AssessmentDraft, id: string, value: AnswerValue | null) {
  const q = questions.find(q => q.id === id)!;
  return updateAnswer(d, q, answerFor(q, value, at));
}
const equipmentQuestions = (d: AssessmentDraft) => activeQuestions(d.answers).filter(q => EQUIPMENT_QUESTION_IDS.some(id => id === q.id)).map(q => q.id);
test("equipment questions adapt to selected equipment and type with explicit unknowns", () => {
  let d = emptyAssessment();
  for (const value of [null, ["none"]]) assert.deepEqual(equipmentQuestions(answer(d, "cooling", value)), []);
  d = answer(d, "cooling", ["fan", "air-conditioner"]);
  assert.deepEqual(equipmentQuestions(d), ["fanType", "acType"]);
  d = answer(d, "fanType", "portable");
  d = answer(d, "acType", "wall-mounted");
  assert.deepEqual(equipmentQuestions(d), [...EQUIPMENT_QUESTION_IDS]);
  assert.equal(canSeeAssessment({ ...d, currentQuestionId: "location" }), false);
  assert.ok(EQUIPMENT_QUESTION_IDS.every(id => sceneFocus(id) === "cooling"));
  d = answer(d, "acType", null);
  assert.deepEqual(equipmentQuestions(d), ["fanType", "portableFanPosition", "acType"]);
  d = answer(d, "fanType", "ceiling");
  assert.deepEqual(equipmentQuestions(d), ["fanType", "acType"]);
});
test("type/equipment edits clear incompatible positions, return to cooling if cursor disappears, and do not restore stale details", () => {
  let d = answer(emptyAssessment(), "cooling", ["fan", "air-conditioner"]);
  d = answer(answer(d, "fanType", "both"), "portableFanPosition", "foot-of-bed");
  d = answer(answer(d, "acType", "window-mounted"), "acWall", "east");
  assert.deepEqual(equipmentPlacement(d.answers), { fanPosition: "foot-of-bed", acType: "window-mounted", acWall: "east" });
  const signature = materialSignature(d);
  d = answer({ ...d, currentQuestionId: "portableFanPosition" }, "fanType", "ceiling");
  assert.equal(d.currentQuestionId, "cooling");
  assert.equal(d.answers.portableFanPosition, undefined);
  d = answer(d, "acType", "portable");
  assert.equal(d.answers.acWall, undefined);
  assert.notEqual(materialSignature(d), signature);
  d = answer(d, "cooling", ["none"]);
  assert.ok(EQUIPMENT_QUESTION_IDS.every(id => !d.answers[id]));
  assert.deepEqual(equipmentPlacement(d.answers), {});
  assert.deepEqual(assessmentScene(d.answers, d.sceneDetails).equipment, []);
});
test("new core follows cooling and persists type and placement in review/transport without inventing values", () => {
  let d = emptyAssessment();
  while (d.currentQuestionId !== "cooling") d = moveAssessment(answer(d, d.currentQuestionId, null), "continue");
  d = moveAssessment(answer(d, "cooling", ["fan", "air-conditioner"]), "continue");
  assert.equal(d.currentQuestionId, "fanType");
  d = moveAssessment(answer(d, "fanType", "portable"), "continue");
  assert.equal(d.currentQuestionId, "portableFanPosition");
  assert.equal(moveAssessment(d, "continue"), d);
  d = moveAssessment(answer(d, "portableFanPosition", "beside-bed"), "continue");
  assert.equal(d.currentQuestionId, "acType");
  d = moveAssessment(answer(d, "acType", "wall-mounted"), "continue");
  assert.equal(d.currentQuestionId, "acWall");
  assert.deepEqual(allowedIntakeQuestions(d), ["acWall"]);
  d = moveAssessment(answer(d, "acWall", "north-west"), "continue");
  assert.equal(canSeeAssessment(d), true);
  const restored: AssessmentDraft = JSON.parse(JSON.stringify(d));
  assert.equal(isAssessmentDraft(restored), true);
  assert.equal(isPlannerCommand({ schemaVersion: 1, operation: "assess", assessment: assessmentInput(restored) }), true);
  assert.deepEqual(equipmentPlacement(restored.answers), { fanPosition: "beside-bed", acType: "wall-mounted", acWall: "north-west" });
  assert.match(equipmentDetailText(restored.answers, "fan"), /Portable fan.*Beside the bed/);
  assert.deepEqual(assessmentScene(restored.answers).equipment, ["split-ac", "portable-fan"]);
  const unsure = answer(restored, "acWall", null);
  assert.equal(equipmentPlacement(unsure.answers).acWall, undefined);
  assert.match(equipmentDetailText(unsure.answers, "air-conditioner"), /Not sure/);
});
test("legacy completed records with individual windows retain answers and resume equipment questions", () => {
  let d = answer(emptyAssessment(), "windowCount", 1);
  for (const q of activeQuestions(d.answers).filter(q => CORE_QUESTION_IDS.some(id => id === q.id) && !EQUIPMENT_QUESTION_IDS.some(id => id === q.id))) if (!d.answers[q.id]) d = answer(d, q.id, q.id === "cooling" ? ["fan"] : null);
  d = { ...d, currentQuestionId: "location", completed: true };
  assert.equal(isAssessmentDraft(d), true);
  const restored = resumeAssessment(d);
  assert.equal(restored.currentQuestionId, "fanType");
  assert.equal(restored.completed, false);
  assert.deepEqual(restored.answers, d.answers);
});
test("diagram confirmation preserves unchanged positions, updates types, and unknown manual types override saved scenes", () => {
  let d = answer(emptyAssessment(), "cooling", ["fan", "air-conditioner"]);
  d = answer(answer(d, "fanType", "portable"), "portableFanPosition", "near-door");
  d = answer(answer(d, "acType", "window-mounted"), "acWall", "south");
  d = confirmScene(d, assessmentScene(d.answers), at);
  assert.equal(equipmentPlacement(d.answers).acWall, "south");
  assert.equal(equipmentPlacement(d.answers).fanPosition, "near-door");
  d = confirmScene(d, { ...assessmentScene(d.answers), equipment: ["split-ac", "ceiling-fan"] }, at);
  assert.equal(equipmentPlacement(d.answers).fanPosition, undefined);
  assert.equal(d.answers.fanType?.status === "known" && d.answers.fanType.value, "ceiling");
  d = answer(answer(d, "fanType", null), "acType", null);
  assert.deepEqual(assessmentScene(d.answers, d.sceneDetails).equipment, ["ac-unspecified", "fan-unspecified"]);
});
