import test from "node:test";
import assert from "node:assert/strict";
import { emptyAssessment, answerFor, updateAnswer } from "../src/features/assessment/state.ts";
import { questions } from "../src/features/assessment/questions.ts";
import { confirmScene } from "../src/features/room-scene/confirm-scene.ts";
import { assessmentScene } from "../src/features/room-scene/assessment-scene.ts";
import { emptyScene } from "../src/contracts/room-scene.ts";
import { assessmentInput, calculationDraft } from "../src/contracts/journey.ts";
import { isPlannerCommand, isPlannerResult } from "../src/contracts/validation.ts";
import { executePlanner } from "../src/services/journey-adapters.ts";
import { materialSignature } from "../src/domain/material-signature.ts";
const at = "2026-10-03T08:00:00Z";
const scene = { ...emptyScene(), windows: [{direction:"west" as const, shade:"awning" as const, covering:"blinds" as const}, {direction:"east" as const, shade:"unknown" as const, covering:"unknown" as const}] };
test("confirmed individual room facts survive validated backend round trip including mixed unknowns", () => {
  const draft = confirmScene(emptyAssessment(), scene, at);
  const command = JSON.parse(JSON.stringify({schemaVersion:1, operation:"assess", assessment:assessmentInput(draft)}));
  assert.equal(isPlannerCommand(command), true);
  assert.deepEqual(assessmentScene(calculationDraft(command.assessment).answers, command.assessment.sceneDetails), scene);
  const result = executePlanner(command);
  assert.equal(isPlannerResult(result), true);
  assert.ok(result.ok && result.data.profile.windows.status === "known");
  const [first, second] = result.data.profile.windows.value;
  assert.equal(first?.orientation.status === "known" && first.orientation.value, "west");
  assert.equal(first?.externalShading.status === "known" && first.externalShading.value, true);
  assert.equal(first?.internalCoverings.status === "known" && first.internalCoverings.value, "blinds");
  assert.equal(second?.externalShading.status, "unknown");
  assert.equal(first?.opens.status, "unknown");
  command.assessment.sceneDetails.scene.windows[0].shade = "invented";
  assert.equal(isPlannerCommand(command), false);
});
test("new answers override saved individual shading, and zero windows remains an empty backend list", () => {
  let draft = confirmScene(emptyAssessment(), scene, at);
  const original = materialSignature(draft);
  const q = questions.find(q=>q.id === "externalShading")!;
  draft = updateAnswer(draft, q, answerFor(q, "none", at));
  assert.notEqual(materialSignature(draft), original);
  const result = executePlanner({schemaVersion:1,operation:"assess",assessment:assessmentInput(draft)});
  assert.ok(result.ok && result.data.profile.windows.status === "known");
  assert.ok(result.data.profile.windows.value.every(w=>w.externalShading.status === "known" && w.externalShading.value === false));
  const zero = confirmScene(draft, {...emptyScene(), windows:[]}, at);
  const empty = executePlanner({schemaVersion:1,operation:"assess",assessment:assessmentInput(zero)});
  assert.ok(empty.ok && empty.data.profile.windows.status === "known");
  assert.deepEqual(empty.data.profile.windows.value, []);
});
