import { billFields, type Bill, type BillKey, type ConfirmedBill } from "@/contracts/energy-assistant";
import { billMeasures, isUnknownAnswer, opportunities, questionTitles, type Household } from "./logic";
import { sources, techniques } from "@/features/knowledge-base/catalogue";
import type { EnergyAdvice } from "@/contracts/energy-analysis";
import Link from "next/link";
import styles from "./energy-assistant.module.css";
const importantFields: BillKey[] = ["periodStart", "periodEnd", "billingDays", "consumptionKwh", "totalAmountAud", "usageRateAud", "supplyDailyAud"];
export function BillDetails({ bill, correctedFields = [], reviewed = false }: { bill: Bill; correctedFields?: BillKey[]; reviewed?: boolean }) {
  const rows = (keys: BillKey[]) => <dl className={styles.facts}>{keys.map(k => <div key={k}><dt>{billFields[k].label}</dt><dd>{bill[k].value === null ? "Not found on this bill" : `${bill[k].value} ${billFields[k].unit}`}<small>{bill[k].value === null ? "Not supplied" : correctedFields.includes(k) ? "Reported by you" : k === "consumptionKwh" && bill.consumptionCalculation ? `Added from bill usage rows · ${reviewed ? "confirmed by you" : "please check"}` : reviewed ? "Extracted from bill · confirmed by you" : "Extracted from bill · please check"}</small>{k === "consumptionKwh" && bill.consumptionCalculation && <details><summary>How we added your usage</summary><p>{bill.consumptionCalculation.componentIndexes.map(index => `${bill.tariffComponents?.[index]?.label}: ${bill.tariffComponents?.[index]?.consumptionKwh} kWh`).join(" + ")} = {bill.consumptionKwh.value} kWh. Solar exports are separate.</p>{bill.consumptionCalculation.componentIndexes.map(index => <p key={index}>{bill.tariffComponents?.[index]?.evidence}</p>)}</details>}{bill[k].evidence && <details><summary>Bill excerpt</summary><p>{bill[k].evidence}</p></details>}</dd></div>)}</dl>;
  return <>{rows(importantFields)}<details><summary>Retailer, solar, tariffs and other details</summary>{rows((Object.keys(billFields) as BillKey[]).filter(k => !importantFields.includes(k)))}{(bill.tariffComponents?.length ?? 0) > 0 && <><p>Tariff rows are kept separately; no average usage rate is calculated.</p><dl className={styles.facts}>{bill.tariffComponents?.map((t, index) => <div key={`${t.kind}-${index}`}><dt>{t.label}</dt><dd>{t.rateAudPerKwh === null ? "Rate unknown" : `${t.rateAudPerKwh} AUD/kWh`}{t.consumptionKwh !== null && <small>{t.consumptionKwh} kWh · bill row, not appliance use</small>}{t.amountAud !== null && <small>{t.amountAud} AUD</small>}<details><summary>Bill excerpt</summary><p>{t.evidence}</p></details></dd></div>)}</dl></>}</details></>;
}
export function EnergyAnalysis({ confirmed, household, advice, pending = false }: { confirmed: ConfirmedBill; household: Household; advice: EnergyAdvice | null; pending?: boolean }) {
  const result = billMeasures(confirmed), actions = opportunities(household);
  return <article className={styles.analysis} aria-labelledby="analysis-title">
    <span className={styles.eyebrow}>YOUR BILL · WHOLE PROPERTY</span><h2 id="analysis-title">Your electricity, at a glance.</h2>
    <dl className={styles.metrics}>
      <div><dt>Electricity imported</dt><dd>{confirmed.bill.consumptionKwh.value ?? "Unknown"} {confirmed.bill.consumptionKwh.value !== null && <span>kWh</span>}</dd><small>{result.days === null ? "Billing period unknown" : `Over ${result.days} days · confirmed bill`}</small></div>
      <div><dt>Daily average</dt><dd>{result.kwhPerDay === null ? "Unknown" : <>≈ {result.kwhPerDay.toFixed(1)} <span>kWh / day</span></>}</dd><small>{result.kwhPerDay === null ? "Needs imported electricity and billing days" : "Calculated from your confirmed details"}</small></div>
    </dl>
    <small>{result.daysBasis}. This is a factual measure, without a high or low usage classification.</small>
    {pending ? <div role="status" className={styles.analysisLoading}><strong>Looking at the whole picture</strong><p>Reading the bill alongside your answers to find useful next steps…</p><span /><span /><span /></div> : advice ? <>
      <h3>What stands out in your bill</h3><p>{advice.summary}</p>
      <div className={styles.billNotes}>{advice.billNotes.map((note, index) => <section key={index}><h4>{note.title}</h4><p>{note.explanation}</p><details><summary>See it on your bill</summary><blockquote>{note.evidence}</blockquote></details></section>)}</div>
      <h3>Your next small changes</h3><ol className={styles.actions}>{advice.recommendations.map((item, index) => {
        const technique = techniques.find(t => t.id === item.techniqueId);
        return <li key={index}><div className={styles.actionHeading}><h4>{item.title}</h4><span>{index === 0 ? "Start here" : "Worth exploring"}</span></div><p>{item.reason}</p><p className={styles.nextStep}><strong>How to try it</strong>{item.action}</p><details><summary>Before you start</summary><p>{item.check}</p>{technique?.checks.map(check => <p key={check}>{check}</p>)}</details>{technique && <><Link href={`/knowledge-base#${technique.id}`}>Explore the practical guide →</Link><p>{technique.sourceIds.map(id => <a key={id} href={sources[id].url} target="_blank" rel="noreferrer">{sources[id].title} ↗ </a>)}</p></>}</li>;
      })}</ol>
      {advice.uncertainties.length > 0 && <details><summary>What still needs checking</summary><ul>{advice.uncertainties.map((item, index) => <li key={index}>{item}</li>)}</ul></details>}
    </> : <><h3>Practical starting points</h3><p>These use your reported household details. The full bill explanation can be retried below.</p>
    {actions.length ? <ol className={styles.actions}>{actions.map(a => <li key={a.title}><div className={styles.actionHeading}><h4>{a.title}</h4><span>{a.priority}</span></div><p>{a.why}</p><p className={styles.nextStep}><strong>Your next step</strong>{a.action}</p><details><summary>Your context & what to check</summary><p><strong>Reported:</strong> {a.reported}</p><p><strong>Unknown:</strong> {a.unknown}</p></details><a href={sources[a.sourceId].url} target="_blank" rel="noreferrer">{sources[a.sourceId].title} ↗</a>{a.heatLink && <p>Reducing heat entering the home can reduce cooling demand. <Link href="/assessment">Investigate room heat with Home Heat Planner →</Link></p>}</li>)}</ol> : <p>There isn’t enough specific load information to prioritise an appliance. Start by identifying the major systems in use and collecting their schedules or energy records. <Link href="/knowledge-base">Browse reviewed household guidance →</Link></p>}
    </>}
    <details><summary>What we know — confirmed bill details</summary><BillDetails bill={confirmed.bill} correctedFields={confirmed.correctedFields} reviewed /></details>
    <details><summary>What you told me — household information</summary><dl className={styles.reports}>{Object.entries(household).map(([key, value]) => <div key={key}><dt>{questionTitles[key as keyof Household]}</dt><dd>{isUnknownAnswer(value) ? "Unknown — not established from your answers." : `Reported: ${value}`}</dd></div>)}</dl></details>
    <h3>What we don’t know</h3><p>The bill does not measure each appliance or bedroom. {result.unallocatedKwh === null ? "Total imported consumption is unknown." : `All ${result.unallocatedKwh} kWh remain unallocated to individual loads.`} No appliance-use estimates, savings, payback or temperature reductions have been calculated. Solar exports, when present, do not establish total electricity used inside the home.</p>
  </article>;
}
