import type { MarketplaceReward } from "./model.ts";

/** Illustrative offers only. No company, cash value or fulfilment is represented. */
export const demoRewards: readonly MarketplaceReward[] = [
  { id: "pedestal-fan", name: "Energy-efficient pedestal fan", category: "Home comfort", points: 650, description: "A little extra comfort for the spaces you spend time in.", detail: "An illustrative pedestal fan reward for use in occupied rooms. A real offer would need model details, suitability checks and product terms; none is supplied in this prototype." },
  { id: "energy-plug", name: "Smart energy-monitoring plug", category: "Energy", points: 400, description: "Get curious about how much electricity a plug-in appliance uses.", detail: "A demonstration of a plug-in energy monitor reward. Any future product would need Australian electrical compliance and appliance compatibility checks. Monitoring alone does not establish energy savings." },
  { id: "curtain-voucher", name: "Thermal curtain voucher", category: "Home comfort", points: 700, description: "Explore thermal or blackout coverings that suit your windows.", detail: "An illustrative voucher towards window coverings. Measurements, fitting and the right covering for your room would need checking. No supplier, voucher value or cooling-performance guarantee is included." },
  { id: "draught-kit", name: "Draught-sealing home kit", category: "Home comfort", points: 350, description: "A practical starting point for checking unwanted gaps at home.", detail: "A prototype kit concept for suitable door and window gaps. Keep required ventilation clear and check suitability before sealing anything. This demonstration does not supply a physical kit." },
  { id: "electricity-credit", name: "Electricity bill credit", category: "Energy", points: 900, description: "Imagine putting your household actions towards a future bill.", detail: "A demo partner-style bill credit concept. No retailer is involved, no dollar value is assigned and no credit is applied to an electricity account." },
  { id: "internet-credit", name: "Home internet plan credit", category: "Everyday essentials", points: 1000, description: "An everyday household reward, beyond your room plan.", detail: "A prototype credit towards a household internet plan. No internet provider is a partner, and this demonstration does not change a plan or issue a real credit." },
  { id: "ac-service", name: "Air-conditioner service voucher", category: "Services", points: 850, description: "Explore professional care for an existing air conditioner.", detail: "A demo voucher concept for a qualified professional to assess and service an existing AC. Scope, equipment suitability and service terms would need confirmation. No booking or service is provided." },
  { id: "home-assessment", name: "Home energy assessment", category: "Services", points: 1100, description: "A fresh perspective on your home and the next steps to investigate.", detail: "An illustrative professional assessment reward. A future service could review the home and discuss suitable improvements. This prototype does not arrange an assessor or certify home performance." },
  { id: "insulation-credit", name: "Insulation assessment credit", category: "Services", points: 1200, description: "Put understanding your ceiling and roof insulation on the list.", detail: "A demonstration credit concept towards a qualified insulation assessment. It does not assume insulation is missing or authorise roof-space access. No appointment, upgrade or financial credit is included." },
  { id: "efficiency-voucher", name: "Home efficiency upgrade voucher", category: "Everyday essentials", points: 1500, description: "Keep a useful household improvement in sight as you take action.", detail: "A prototype voucher concept towards a suitable household efficiency improvement. Real products, permissions and offer terms would need checking. No supplier or dollar value is represented." },
];
