import type { MarketplaceReward } from "./model.ts";

/** Real retailer links checked 4 October 2026. Coins are demo rules, not AUD prices. */
export const demoRewards: readonly MarketplaceReward[] = [
  { id: "thermometer", name: "Holman Thermometer and Hygrometer", category: "Energy", points: 200, retailer: "Bunnings", url: "https://www.bunnings.com.au/holman-thermometer-and-hygrometer_p3130792", description: "Keep temperature and humidity observations with your room check-ins.", detail: "A temperature and humidity monitor for recording observations. Readings do not establish what caused a change. Check current specifications, availability and price with Bunnings." },
  { id: "draught-kit", name: "Sperling Double Sided Draught Stopper", category: "Home comfort", points: 250, retailer: "Bunnings", url: "https://www.bunnings.com.au/sperling-78cm-double-sided-draught-stopper_p0010722", description: "A removable option for an unwanted gap under a suitable door.", detail: "Check that the 78cm stopper fits your door. Keep required ventilation clear, especially where gas appliances are used. Check suitability and current price with Bunnings." },
  { id: "pedestal-fan", name: "40cm Pedestal Fan — White", category: "Home comfort", points: 350, retailer: "Kmart", url: "https://www.kmart.com.au/product/40cm-pedestal-fan-white-43711369/", description: "Personal airflow where you sit or sleep.", detail: "Fans cool people rather than room air. Use effective cooling when needed for heat safety. Check the current product details, availability and price with Kmart." },
  { id: "curtain-voucher", name: "MAJGULL block-out curtains", category: "Home comfort", points: 450, retailer: "IKEA", url: "https://www.ikea.com/au/en/p/majgull-block-out-curtains-1-pair-grey-with-heading-tape-10417814/", description: "Explore internal coverings for a sun-exposed window.", detail: "Check your window dimensions, curtain fit and hanging hardware. External shading intercepts sunlight before it reaches the glass. Check current details, availability and price with IKEA." },
];
